deployment:
  tasks:
    - export DEPLOYPATH=/home/zenhospi/zenhospitality/backend
    - /bin/cp -R backend/* $DEPLOYPATH/
    - export FRONTPATH=/home/zenhospi/public_html
    - /bin/cp -R frontend/dist/* $FRONTPATH/
    - /home/zenhospi/virtualenv/zenhospitality/backend/3.11/bin/pip install -r $DEPLOYPATH/requirements.txt
    - /home/zenhospi/virtualenv/zenhospitality/backend/3.11/bin/python -m alembic -c $DEPLOYPATH/alembic.ini upgrade head