---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zenhospi/zenhospitality/backend
    - export FRONTPATH=/home/zenhospi/public_html
    - /bin/cp -R backend/* $DEPLOYPATH/
    - /bin/cp -R frontend/dist/* $FRONTPATH/