import { X, Sparkles, ArrowRight, IndianRupee, Loader2, Download } from 'lucide-react';
import { useState } from 'react';
import jsPDF from 'jspdf';
import EnquiryModal from './EnquiryModal';

const COLORS = { green: [0, 200, 150], white: [255, 255, 255], gray: [100, 100, 100], dark: [50, 50, 50], light: [180, 180, 180] };

const ItineraryModal = ({ itinerary, loading, onClose }) => {
  const [showEnquiry, setShowEnquiry] = useState(false);
  const [pdfLoading, setPdfLoading] = useState(false);

  const handleDownloadPdf = () => {
    if (!itinerary) return;
    setPdfLoading(true);

    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pw = pdf.internal.pageSize.getWidth();
      let y = 20;

      const addIfNeeded = (needed) => { if (y + needed > 280) { pdf.addPage(); y = 20; } };
      const sectionTitle = (text) => { pdf.setFontSize(14); pdf.setTextColor(...COLORS.green); pdf.text(text, 15, y); y += 8; };
      const bodyText = (text, opts = {}) => { pdf.setFontSize(opts.size || 10); pdf.setTextColor(...(opts.color || COLORS.dark)); pdf.text(text, opts.x || 15, y); y += (opts.h || 6); };

      // ── Header ──
      pdf.setFillColor(...COLORS.green);
      pdf.rect(0, 0, pw, 12, 'F');
      pdf.setFontSize(9);
      pdf.setTextColor(...COLORS.white);
      pdf.text('Zen World Hospitality — AI-Powered Itinerary', 15, 8);
      y = 22;

      // ── Title ──
      pdf.setFontSize(22);
      pdf.setTextColor(...COLORS.dark);
      pdf.text(itinerary.title || 'Your Itinerary', pw / 2, y, { align: 'center' });
      y += 9;
      pdf.setFontSize(10);
      pdf.setTextColor(...COLORS.gray);
      const lines = pdf.splitTextToSize(itinerary.description || '', pw - 30);
      lines.forEach((l) => { pdf.text(l, pw / 2, y, { align: 'center' }); y += 5; });
      y += 6;

      // ── Days ──
      if (itinerary.days) {
        sectionTitle('Your Day-by-Day Plan');
        itinerary.days.forEach((day) => {
          addIfNeeded(30);
          pdf.setFillColor(240, 255, 245);
          pdf.roundedRect(12, y - 3, pw - 24, 7, 1.5, 1.5, 'F');
          pdf.setFontSize(11);
          pdf.setTextColor(...COLORS.green);
          pdf.setFont('helvetica', 'bold');
          pdf.text(`Day ${day.day}: ${day.title}`, 18, y + 2);
          pdf.setFont('helvetica', 'normal');
          y += 11;
          if (day.activities) {
            day.activities.forEach((act) => {
              addIfNeeded(6);
              bodyText(`  •  ${act}`, { x: 18, h: 5.5, color: COLORS.dark });
            });
          }
          y += 3;
        });
      }

      // ── Travel Tips ──
      if (itinerary.travel_tips && itinerary.travel_tips.length > 0) {
        addIfNeeded(30);
        sectionTitle('Travel Tips');
        itinerary.travel_tips.forEach((tip) => {
          addIfNeeded(6);
          bodyText(`  •  ${tip}`, { x: 18, h: 5.5 });
        });
        y += 3;
      }

      // ── Budget ──
      if (itinerary.budget_summary) {
        addIfNeeded(20);
        sectionTitle('Budget Summary');
        const blines = pdf.splitTextToSize(itinerary.budget_summary, pw - 30);
        blines.forEach((l) => { bodyText(l, { color: COLORS.gray }); });
        y += 2;
      }

      // ── Footer ──
      pdf.setFontSize(8);
      pdf.setTextColor(...COLORS.light);
      pdf.text('Generated by Zen World Hospitality AI — zenhospitality.com', pw / 2, 290, { align: 'center' });

      pdf.save(`${(itinerary?.title || 'itinerary').replace(/\s+/g, '_')}.pdf`);
    } catch (err) {
      console.error('PDF generation failed', err);
    } finally {
      setPdfLoading(false);
    }
  };

  return (
    <>
      <div className="fixed inset-0 z-[150] flex items-end sm:items-center justify-center p-0 sm:p-4" onClick={onClose}>
        <div className="absolute inset-0 bg-black/80 backdrop-blur-sm" />
        <div
          className="relative w-full sm:max-w-2xl max-h-[90vh] bg-[#0a0f1c] border border-gray-800 rounded-t-2xl sm:rounded-2xl shadow-2xl overflow-hidden animate-fade-in flex flex-col"
          onClick={(e) => e.stopPropagation()}
        >
          {/* Header */}
          <div className="sticky top-0 z-10 bg-[#0a0f1c] border-b border-gray-800 p-4 md:p-6 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-full bg-gradient-to-br from-emerald-500 to-teal-500 flex items-center justify-center">
                <Sparkles className="w-5 h-5 text-white" />
              </div>
              <div>
                <h3 className="text-lg md:text-xl font-playfair font-bold text-white">Your AI Itinerary</h3>
                <p className="text-xs text-gray-400">Powered by Gemini AI</p>
              </div>
            </div>
            <button onClick={onClose} className="text-gray-400 hover:text-white transition-colors p-1.5 hover:bg-gray-800 rounded-lg">
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Content */}
          <div className="overflow-y-auto p-4 md:p-6 space-y-4">
            {loading ? (
              <div className="flex flex-col items-center justify-center py-16">
                <Loader2 className="w-10 h-10 text-emerald-400 animate-spin mb-4" />
                <p className="text-gray-400 text-sm">Crafting your personalized itinerary...</p>
              </div>
            ) : itinerary ? (
              <>
                {/* Title Section */}
                <div className="glass-card p-4 md:p-6 rounded-xl border border-emerald-500/20 bg-gradient-to-br from-emerald-500/5 to-transparent">
                  <h4 className="text-xl md:text-2xl font-playfair font-bold text-white mb-1">{itinerary.title}</h4>
                  <p className="text-gray-400 text-sm">{itinerary.description}</p>
                </div>

                {/* Days */}
                <div className="space-y-3">
                  {itinerary.days?.map((day, idx) => (
                    <div key={idx} className="glass-card rounded-xl border border-gray-800 overflow-hidden hover:border-emerald-500/30 transition-colors">
                      <div className="flex items-center gap-3 p-3 md:p-4 bg-gray-800/40 border-b border-gray-800">
                        <div className="w-8 h-8 md:w-10 md:h-10 rounded-full bg-gradient-to-br from-emerald-500 to-teal-500 text-white shrink-0 flex items-center justify-center font-bold text-xs md:text-sm shadow-[0_0_10px_rgba(16,185,129,0.3)]">
                          {day.day}
                        </div>
                        <div>
                          <div className="font-bold text-white text-sm md:text-base">Day {day.day}: {day.title}</div>
                        </div>
                      </div>
                      <div className="p-3 md:p-4">
                        <ul className="space-y-2">
                          {day.activities?.map((act, i) => (
                            <li key={i} className="flex items-start gap-2.5 text-xs md:text-sm text-gray-400">
                              <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 mt-1.5 flex-shrink-0" />
                              {act}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  ))}
                </div>

                {/* Travel Tips */}
                {itinerary.travel_tips?.length > 0 && (
                  <div className="glass-card p-4 md:p-5 rounded-xl border border-emerald-500/10 bg-emerald-500/5">
                    <p className="text-emerald-400 text-sm font-semibold mb-2 flex items-center gap-1.5">
                      <Sparkles className="w-4 h-4" /> Travel Tips
                    </p>
                    <ul className="space-y-1.5">
                      {itinerary.travel_tips.map((tip, i) => (
                        <li key={i} className="flex items-start gap-2 text-xs md:text-sm text-gray-400">
                          <span className="text-emerald-500 mt-0.5">•</span> {tip}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Budget Summary */}
                {itinerary.budget_summary && (
                  <div className="glass-card p-4 md:p-5 rounded-xl border border-emerald-500/10 bg-emerald-500/5">
                    <p className="text-emerald-400 text-sm font-semibold mb-2 flex items-center gap-1.5">
                      <IndianRupee className="w-4 h-4" /> Budget Summary
                    </p>
                    <p className="text-sm text-gray-300">{itinerary.budget_summary}</p>
                  </div>
                )}
              </>
            ) : (
              <div className="text-center py-16 text-gray-500">
                <p className="text-sm">No itinerary data available.</p>
              </div>
            )}
          </div>

          {/* Footer */}
          {itinerary && !loading && (
            <div className="sticky bottom-0 z-10 bg-[#0a0f1c] border-t border-gray-800 p-4 md:p-6 flex justify-between items-center gap-4">
              <p className="text-xs text-gray-500 hidden sm:block">Ready to book this trip?</p>
              <div className="flex items-center gap-3">
                <button onClick={handleDownloadPdf} disabled={pdfLoading} className="px-4 py-3 bg-gray-800 hover:bg-gray-700 text-white rounded-xl font-medium transition-all flex items-center justify-center gap-2 text-sm border border-gray-700 hover:border-emerald-500">
                  {pdfLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
                  {pdfLoading ? 'Generating PDF...' : 'Download PDF'}
                </button>
                <button onClick={() => setShowEnquiry(true)} className="px-6 py-3 bg-gradient-to-r from-emerald-600 to-teal-500 hover:from-emerald-500 hover:to-teal-400 text-white rounded-xl font-medium transition-all flex items-center justify-center gap-2 text-sm">
                  Book This Itinerary <ArrowRight className="w-4 h-4" />
                </button>
              </div>
            </div>
          )}
        </div>
      </div>

      {showEnquiry && (
        <EnquiryModal
          isOpen={showEnquiry}
          onClose={() => setShowEnquiry(false)}
          pkg={{ title: itinerary?.title || 'Custom AI Itinerary' }}
        />
      )}
    </>
  );
};

export default ItineraryModal;
